name: Build wheels

on:
  push:
    branches: [main]
    tags:
      - "v*"
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false    
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3

      - name: Install RTools Windows # https://github.com/scipy/scipy/blob/main/.github/workflows/windows.yml
        if: contains(matrix.os, 'windows')
        run: |
          choco install rtools --no-progress
          echo "c:\rtools40\mingw64\bin;" >> $env:GITHUB_PATH
          echo "c:\rtools40\usr\bin;" >> $env:GITHUB_PATH
      - name: Install OpenBLAS for Windows
        if: contains(matrix.os, 'windows')
        run: |
          pacman -Sy
          pacman -S mingw-w64-x86_64-openblas --noconfirm
          echo "c:\rtools40\mingw64\lib;" >> $env:GITHUB_PATH
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.8.1
        env:
          CIBW_BUILD_VERBOSITY: 1
          CIBW_ARCHS_MACOS: x86_64
          CIBW_ENVIRONMENT_MACOS: CC=clang CXX=clang FC=gfortran-11
          CIBW_BEFORE_BUILD_LINUX: yum -y install openblas-devel
          CIBW_ARCHS: auto64
          CIBW_SKIP: skip = pp* *-musllinux*

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build sdist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v3
        with:
          path: dist/*.tar.gz

  upload_pypi:
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: artifact
          path: dist

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}